version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - run: echo 'VAR=true' | sudo tee /etc/profile.d/pickup.sh
      - run: sudo chmod a+x /etc/profile.d/pickup.sh
      - run: echo $VAR
workflows:
  default:
    jobs:
      - build
