version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - run: echo 'export VAR=true' | tee $BASH_ENV
      - run: env
workflows:
  default:
    jobs:
      - build
